name: Count TILs

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "!README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count TILs
        run: echo "TILS_COUNT=$(find . -name '*.md' -not -name 'README.md' | wc -l)" >> $GITHUB_ENV
      - name: Update README.md
        run: sed -i "s@<code>[0-9]*</code>@<code>$TILS_COUNT</code>@g" README.md
      - name: Commit changes
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add -A; \
            git commit -m "docs: auto-update with latest TILs count"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
